name: Build

on:
  push:
    branches: ["main", "action-test"]
  pull_request:
    branches: ["main", "action-test"]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile

      - shell: bash
        run: |
          set -o braceexpand
          npm config set script-shell bash
          pnpm list sharp @11ty/eleventy-img
          node -p "process.platform + ' ' + process.arch"
          find . -type f | grep -Ei '\.(avif|heic|heif|jxl|tiff?|bmp|ico|webp|jpe?g|png|gif|svg)$' | sort
          pnpm build

      - uses: actions/upload-artifact@v4
        with:
          name: pxl-prod-artifact
          path: dist
      # - run: pwd && ls -lah
