name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "action-test"]
  pull_request:
    branches: ["main", "action-test"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        shell: bash
        run: |
          set -o braceexpand
          npm config set script-shell bash
          pnpm build

      - run: |
          chmod -c -R +rX ./dist | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
      # - run: pwd && ls -lah
  deploy:
    needs: build

    runs-on: catthehacker/ubuntu:runner-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
